# vim: ft=yaml.jinja

version: "3.9"

services:
  redis:
    image: redis:latest

  postgres:
    image: postgres:15
    volumes:
      - db:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: investigraph
      POSTGRES_USER: investigraph
      POSTGRES_DB: investigraph

  server:
    image: ghcr.io/investigativedata/investigraph:latest
    ports:
      - 127.0.0.1:4200:4200
    depends_on:
      - postgres
      - redis
    volumes:
      - data:/data/prefect
      - ./datasets:/data/local/datasets
    env_file:
      investigraph.env

  agent:
    image: ghcr.io/investigativedata/investigraph:latest
    command: prefect agent start -q 'default'
    depends_on:
      - server
    env_file:
      investigraph.env


volumes:
  db:
  data:
