[project]
name = "investigraph"
version = "0.9.0"
description = "etl pipeline for investigations with follow the money data"
authors = [{ name = "Simon Wörpel", email = "simon.woerpel@pm.me" }]
license = "MIT"
readme = "README.md"
classifiers = [
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
requires-python = ">=3.11,<3.15"
dependencies = [
    "anystore (>=1.2.7,<2.0.0)",
    "ftmq (>=5.0.0,<6.0.0)",
    "runpandarun (>=0.8.1,<0.9.0)",
    "dateparser (>=1.2.2,<2.0.0)",
    "followthemoney (>=4.10.2,<5.0.0)",
    "memorious4 (>=4.1.0,<5.0.0)",
    "ftm-lakehouse (>=0.5.1,<0.6.0)",
    "rigour (>=2.3.1,<3.0.0)",
]

[project.optional-dependencies]
sql = ["sqlalchemy (>=2.0.36,<3.0.0)"]
postgres = ["sqlalchemy (>=2.0.36,<3.0.0)", "psycopg2 (>=2.9.10,<3.0.0)"]
redis = ["redis (>=4.0.0)"]
level = ["plyvel (>=1.5.1,<2.0.0)"]

[project.scripts]
investigraph = "investigraph.cli:cli"

[project.urls]
Homepage = "https://investigraph.dev"
Repository = "https://github.com/dataresearchcenter/investigraph-etl"
Documentation = "https://docs.investigraph.dev"
Issues = "https://github.com/dataresearchcenter/investigraph-etl/issues"

[tool.poetry.group.dev.dependencies]
pytest-env = ">=1.1.1"
pytest = ">=9.0.3,<10.0.0"
pytest-cov = ">=4.1,<7.0"
black = ">=23.11,<25.0"
isort = "^5.12.0"
mypy = "^2.1.0"
pre-commit = ">=3.5,<5.0"
flake8 = ">=6.1,<8.0"
bump2version = "^1.0.1"
mkdocs-material = "^9.6.14"
mkdocs-autorefs = "^1.4.2"
mkdocstrings-python = "^2.0.7"
griffe-pydantic = "^1.1.0"
mkdocs = "^1.6.1"
mkdocs-typer2 = "^0.1.4"
ipython = "^9.10.0"
pytest-xdist = "^3.8.0"
griffe = "<2"
ipdb = "^0.13.13"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest_env]
DEBUG = 1
INVESTIGRAPH_DATA_ROOT = ".test"
NOMENKLATURA_DB_URL = "sqlite:///:memory:"
FTM_STATEMENT_STORE = "memory://"
